name: build

on:
  push:
    tags:
      - '**'

env:
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # reads history for commit changelog

      - name: Build packages
        uses: BigWigsMods/packager@v2
